name: Validate json files
on:
  pull_request:
    branches: [ "develop", "main"]
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Validate json files
      uses: RaaLabs/validate-json@v1.0.1
      with:
        directory: "."