name: Issue Opened/Edited
on:
  issues:
    types:
      - opened
      - edited
jobs:
  test-issue:
    name: Validate Issue
    runs-on: ubuntu-latest
    steps:
      - name: Output Validation Results
        run: echo 'The label was bug'
