name: Run Actions when issue was created
on:
  issues:
    types:
      - opened
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          MY_NAME: "Abhishek"
